---
- name: copy-file
  hosts: target-vm
  become: true
  tasks:

  - name: file-copy-to-target
    ansible.builtin.copy:
      src: /home/einfochips/Documents/ansible-vm-code/if-opreting-system-wise.yaml
      dest: /home/shital/Documents/my.yaml
      owner: shital
      group: shital
      mode: '644'

  - name: add-custom-data
    lineinfile:
      path: /home/shital/Documents/my.yaml
      line: "file is changed"

  - name: change this to THIS
    lineinfile:
      path: /home/shital/Documents/my.yaml
      regexp: '/bthis/b'
      line: 'THIS'

