---
- name: condition-based
  hosts: target-vm
  gather_facts: true
  tasks:

  - name: check if Ubuntu
    debug: 
      msg: "this from linux"
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
  - name: check if RedHat
    debug: 
      msg: "this from RedHat"
    when: ansible_distribution == 'RedHat'