---
- name: loopexample
  hosts: target-vm
  tasks:
    - name: create a file if not exist
      file:
        path: /home/Desktop/
        state: directory

    - name: create file
      file:
        path: /home/Desktop/loop.txt
        state: touch

    - name: 
      lineinfile:
        path: /home/Desktop/loop.txt
        line: "this {{ item }}"
      with_items:
        - banana
        - apple
        - pienepal
